[workspace]
authors = ["r1cheu <chenrulei@cemps.ac.cn>"]
channels = ["conda-forge", "bioconda"]
name = "vcf_to_map"
platforms = ["linux-64"]
version = "0.1.0"


[dependencies]
htslib = ">=1.22,<2"
liblzma-static = ">=5.8.1,<6"

[build-dependencies]
cmake = ">=3.18,<4"
cxx-compiler = ">=1.8.0,<2"
ninja = ">=1.12.1,<2"

[tasks.configure]
cmd = ["cmake", "-GNinja", "-S .", "-B.build"]
inputs = ["CMakeLists.txt"]
outputs = [".build/CMakeFiles"]

[tasks.build]
cmd = ["cmake", "--build", ".build"]
depends-on = ["configure"]
inputs = ["CMakeLists.txt", "main.cpp"]
outputs = [".build/vcf_combine"]
